### ISSUE TITLE
Giveth.io Integration -- Platform for building Decentralized Charitable Organizations (DCO) <Looking for help, PM @danip>

### ISSUE THREAD

**Issue by daniphilia** [status-im/hackathon#124]
### Status Hackathon Submission

Website: Giveth.io (info) // dapp.giveth.io (dapp)
Type:  Existing DApp / Bot / Commands

Description: The Giveth platform will allow DCOs to automate accounting, global fund distribution, and many other services that are usually best served by large charities because of economies of scale.

A DCO enables Donors and Change Makers to work together to crowdsource powerful solutions under their own chosen governance and incentive structures to bring more impact for their unique set of resources.

Creating: **In Progress**

Team Members:

Preferred Name: Dani
Github Handle: @daniphilia
Slack Username: @danip
Twitter Handle: @daniphilia

We're looking for more devs to come help us build awesome bots and UI's! DM me @danip or Griff @griff

**Comment by pasupulaphani** [comment]
@daniphilia you guys still looking for help. Checked out giveth.io . I like the idea.
