### ISSUE TITLE
Status app for Android

### ISSUE THREAD

**Issue by ivaf** [status-im/hackathon#146]
### Status Hackathon Submission

Type: 
Github Repo: 
Description:

Team Members:

Hello!

Preferred Name: Ivan
Github Handle: @ivaf
Slack Username: @ivaf
Twitter Handle *optional*: @Petroff_ff

Test app for Android. The problem is the following:
- cannot copy the passphrase to recover my account. If I try long press on it the application closes;
- when I receive on my smartphone an SMS with the confirmation code the app is closes (probably while trying to automatically insert code from SMS);
- a very large flow of traffic. During these two failed launch, the app has used up my daily supply of traffic (over 100 MB).
After a series of restarts managed to copy the phrase to recover your account. Yay! :)
Question: is this normal behavior for an Android app at this stage?

**Comment by benmorrow** [comment]
Hi Ivan, can you ask these questions in the #hackathon channel on [our Slack](http://slack.status.im/)?

**Comment by ivaf** [comment]
Hi!
Yes, I ask this question in the #hackaton channel. There said to ask here :)
Let's close this issue. The next version will be better )))
