### ISSUE TITLE
Unconf - Decentralized Unconference Planner

### ISSUE THREAD

**Issue by salis** [status-im/hackathon#17]
### Status Hackathon Submission

**Type:** DApp + Bot
**Github Repo:** https://github.com/BlockchainLabsNZ/Unconf-DApp

**Description:**
A way to gather a community to plan an Unconference with a few smart contracts providing a lightweight governance model.

**Why:**
1. Because the Unconference format aligns very well with the decentralized Blockchain philosophy.
2. Because Status.im enables the group chat collaboration and location discovery to bring this DApp to life
3. Because BlockchainLabs.nz and Blockchain.org.nz are planning a Blockchain Unconference later this year ;)

**What:**
At a minimum someone should be able to create an Unconference event with a location & date for it to be discoverable in Status.im. People should be able to register (free or paid) and be added to a group chat for collaboration. People should be able to suggest topics they would like to share, and then let others upvote the suggestions.

**Team Members:**

Preferred Name: Paul
Github Handle: @salis
Slack Username: @salis
Twitter Handle: @paulsalis

Preferred Name: Klaus
Github Handle: @janther
Slack Username: @janther
Twitter Handle: @KlausHott

Preferred Name: Isaac
Github Handle: @isaacpayne
Slack Username: @isaac2

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
