### ISSUE TITLE
DApp | Financial Inclusion

### ISSUE THREAD

**Issue by yalu** [status-im/hackathon#19]
Description: Somehow combine mifosX (mifos.org -Mifos X is an extended platform for delivering the complete range of financial services needed for an effective financial inclusion solution.) and status.

Links:
- https://github.com/openMF/community-app
- https://github.com/openMF/incubator-fineract
- https://github.com/openMF/android-client
- https://github.com/mifosio

Team Members:
1. Yalu @yalu '(Github, Slack, Twitter)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by yalu** [comment]
I am way underprepared for this at the moment.
