### ISSUE TITLE
MeDao

### ISSUE THREAD

**Issue by ChicoBitcoinJoe** [status-im/hackathon#21]
### MeDao

Github Repo: https://github.com/ChicoBitcoinJoe/MeDao

Description: This DApp is a new iteration on an idea I call a MeDao. This MeDao lets the creator sell a limited amount of time shares each week and in return is expected to burn a certain amount of tokens as proof of work being done. Some MeDaos may opt out of the burn function altogether. The end goal of this DApp is to give the MeDao creator a free market price for the value of their time. Uses a MiniMe Token for easy and efficient cloning and upgrading.

Functionality includes: set work hours, place and remove a bid to auction, accept the highest bid at auction, and submit proof of work. Some functionality may require a browser refresh in order to update properly.

Temporary Website: http://medao.azurewebsites.net/#/home

Team Members:

Preferred Name: Joseph
Github Handle: chicobitcoinjoe
Slack Username: @chicobitcoinjoe
Reddit Handle *optional*: chicobitcoinjoe

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
