### ISSUE TITLE
Genesis Token Tracker (GTT)

### ISSUE THREAD

**Issue by makoto** [status-im/hackathon#31]
### Status Hackathon Submission

Type: Bot & Dapp
Github Repo:  http://github.com/makoto/gtt

#### Result

-[Demo video](https://youtu.be/biDJBA1UOUc)
-[Dapp URL](http://bit.ly/genesistokentracker) = There is a known issue to be able to view in status.im browser for deployed environment (works on local as shown in the video). To live test, please use Metamask pointing network to Ropsten.

#### Description:

Genesis token tracker(GTT) allows you to keep track of the token allocation of Status Genesis Token (symbol: SGT), an ERC20 token, which will be redeemable for Status Network Tokens (‘SNT’ — also an ERC20 token) when the Network is fully launched.

Why GTT?

From [Encoding the Status ‘Genesis Block’](https://blog.status.im/encoding-the-status-genesis-block-d73d287a750)

> The value that lies within this Network isn’t money, but in thought and actions of the wonderful people of the Ethereum community, those who have shaped not only Status but who I am as well. They are the ones who truly believe in trustless, permissionless and decentralized systems, and what gives web3 meaning. They’ve done so with lengthy discussions, feedback and critiques, contributing to our development and the development of Ethereum, and even by doing community outreach — all these actions have value. But quantifying it is hard, so we intend to do this with our own subjectivity, and establish a web-of-trust.

SGT tokens are awarded to community members and all its transaction history are recorded into Ethereum  [mainnet](https://etherscan.io/token/0xd248b0d48e44aaf9c49aea0312be7e13a6dc1468)  

The immutable contribution history gives a fair and open competition among would be community members. I really like the idea of Genesis token and hope this sets a great standard which other ICO will follow the same path.

What's missing is a handy app to make their activities more visual and transparent, this is where GTT comes in.

With GTT, users can

- see the leaderboard of high token earning people.
- see where user stands in terms of token balance relative to other people via histogram.
- peek through the transaction history of token earnings as well as how they spend/earn eth.

GTT is probably the only dapp&bott on this competition which gives you the real production data despite the fact that status.im is currently running under testnet. This is thanks to Status.im team taking the mirrior of the same transaction history on [testnet](https://ropsten.etherscan.io/token/0x4bda828f1fe628973c39366263b78b7cd9d6d8fe) (hope they continue doing so).

##### Why rendering is so slow?

Because it goes through the contract event every time each user hits. I could add caching layer easily but won't do it during this competition.

##### Why rendering eth transaction history is so much quicker than token history

Because I am cheating by hitting etherscan api. Going through block transaction was too slow to be useful.

##### Will your dapp work without bot?

Yes.

##### Why Bot and Dapp approach?

I initially tried to do everything via bot but quickly figured many of the features (access to contract events, the avility to write messages asnync using `sendEvent`, persist local variables, etc) were not available by the time I was implementing the feature (some of them were fixed during the competition). Rather than trying to spend the whole week debugging, I decided to take the pragmatic approach of building the core feature (charting functions) via Dapp and use Bot to help users navigate the Dapp.

#### Team Members:

For each team member please fill out:
Preferred Name: Makoto
Github Handle: @makoto
Slack Username: @makoto
Twitter Handle *optional*: @makoto_inoue

**Comment by makoto** [comment]
One depending feature to make this work is to be able to listen to whisper message and display the message as it comes. I am currently having difficulty using `status.sendMessage` so this could be a deal breaker to work on this project.

**Comment by makoto** [comment]
It also depends on the ability to be able to call web3 contract from bot, which seems not working right now

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
