### ISSUE TITLE
[Interim Project Name] TLAP

### ISSUE THREAD

**Issue by TomLisankie** [status-im/hackathon#32]
### TLAP

Type: TBD
Github Repo: TBD 
Description: TBD

Team Members:

Preferred Name: Thomas
Github Handle: @TomLisankie
Slack Username: thomas
Twitter Handle: @TomLisankie

Preferred Name: Andrew
Github Handle: @InsidiousMind
Slack Username: insidious

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by TomLisankie** [comment]
We decided to not participate.

**Comment by benmorrow** [comment]
Thanks for closing the issue! See you guys next time 👍
