### ISSUE TITLE
DTP

### ISSUE THREAD

**Issue by gjeanmart** [status-im/hackathon#35]
### Status Hackathon Submission
Type: DApp 
Github Repo: https://github.com/gjeanmart/hackathon
Description: DTS (Decentralized Tutoring System) or MyTutor is a decentralized app (dapp) that bring teachers/tutors and students closer. 

I built this app to help my wife who works as a tutor and always find hard to get new students (she has to work with companies that take huge fees on each course), it's also hard communicate with students, manage the agenda, chase up for the payment, etc. 
That's why comes MyTutor

The dapp is sort of assistant that allows teacher to publish an announce, the student can go through the ads and start chatting with a teacher (feature not available), after Q&A and agreeing a date, time and a price, the teacher can setup a course.
The student has to make a payment into the contract before the course. 
Once the course is finished, the teacher ca either release the payment to his account or refund (if cancelled for example). 
A chabot 

This application is built with:
- Truffle 
- Angular 2
- Ionic 2

Team Members:

Preferred Name: Greg
Github Handle: @gjeanmart
Slack Username: @gregj
Twitter Handle: @gregjeanmart

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
