### ISSUE TITLE
ENS chatbot

### ISSUE THREAD

**Issue by Legogris** [status-im/hackathon#36]
### Status Hackathon Submission
**Description:** A bot (but currently more like a dapp) allowing easy participation and initiation of auctions for ENS domain names.
**GitHub repo:** https://github.com/Legogris/ensbot/

Video: https://www.youtube.com/watch?v=mUtxNbbs0jU

#### Team Members:

Preferred name: Jeff 
Github handle: @jefflau
Slack Username: @jefflau

Preferred Name: Legogris
Github Handle: @legogris
Slack Username: @legogris

Our original ambition was to make a pure, client-side only chatbot. Due to restrictions and snags, we had to add in dapp-components to make it work. Interfacing directly with the ENS contracts on Ropsten.

#### Currently working:

* Checking status of domain name
* Initiating auctions for unclaimed ENS names
* Placing bids in active auctions
* Revealing bids for placed bids

#### Challenges faced:

* Unable to use local testrpc for chatbot
* `webView` and `bridgedWebview` as doesn't render when used as previews for commands
* No eventloop for bots (so no setTimeout, no AJAX requests)
* `sendMessage` not working initially
* No localstorage to remember parameters
* Android `bridgedWebview` doesn't send `Accept` header, which makes `webpackdevserver`'s `historyFallback` fallthrough silently, resulting in 404. 
* Generally very spotty integration with add/update/watch dapp/bot, as well as webview rendering. Sometimes it works, sometimes it doesn't. Server always seems to receive request, but then it doesn't render.

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
