### ISSUE TITLE
WeLottify

### ISSUE THREAD

**Issue by mrtomnguyen** [status-im/hackathon#40]
### Status Hackathon Submission

**Type**: Dapp - New
**Github Repo**: https://github.com/vikas1188/WeLottify/blob/master/WeLottify.sol

**Issues**: 
Unfortunately, dapps from remote server (non-localhost) are not able to make transactions on Status. Things are working on MetaMask. 

**Description**: 
As blockchain supporters, we want to help push mainstream adoption. The mandatory first step is getting users to create an identity and understand how to manage it. Wallets have been moderately successful in attracting first-time users because it involves money and finance. People learn quickly when there’s money on the table. As an extension of that, people become more social and excited when money is then used to take risks like investment or gambling like Augur and Gnosis. Although we do not condone gambling, we do believe in friendly bets and group lottery. Currently, small groups play lottery together without much of a legal framework. There are plenty of sample paper contracts online that can help groups operate better. However, once someone wins the jackpot, lawsuits are not uncommon. There is a better way to do this using Smart Contracts.

**Introducing "Gnosis for Lottery". 
WeLottify is a tool that allows anyone to manage a group lottery using the Ethereum blockchain.** 

Group lottery is not a new concept and neither is lottery using blockchain. Currently, there are sites that claims to use an internal independent algorithm to generate a lottery. There are also services that acts as the authority to buy lottery tickets and then sell seats to players with fiat and bitcoin. It is important to note that WeLottify are different in both ways:
 
1. by using existing lotteries, more people will understand it and more players will join because of the size of the jackpot from day one 
2. by empowering existing groups to operate on their own, the risk is greatly lower as more consumers learn about the blockchain
 
Here’s how it works:
 
1. User creates a Pool by entering details like Name, Lottery (Powerball for now), Drawing Date, Number of Players, Service Fees, and select Public/Private
2. User becomes the Leader to buy the lottery tickets
3. Smart Contracts set a few timed conditions like group closed and upload Proofs time limit
4. Each player can join by committing the Ticket + Fee amount via Bitcoin to be held in escrow
5. If the number of players is reached before the closed time, the Fund is released to the Leader
6. Leader has 24 hrs to buy tickets and upload photos of Proofs to the blockchain like receipts, signed ticket front / back, etc.
7. After the drawing date, the Leader has the responsibility to claim the prize money and distribute equally to the group via bitcoin
 
Initially, we envision that WeLottify will be used in small local circles among family, friends, and co-workers where there’s already a high level of trust. As identity becomes better with more ways to validate them via verifiable claims etc, WeLottify can become a global phenomenon. Anyone in the world can play with peace of mind.
 
Why this is great for blockchain:
 
1. This is a great teaching moment for blockchain as more people will share among their networks and educate each other on identity and bitcoin
2. This can increase the market cap of Bitcoin as large winnings are distributed. Imagine a Jackpot of $375 million being converted into BTC.
3. There is an opportunity for wealth redistribution to help those in poverty as anyone can reap the monetary benefits of a first-world lottery. WeLottify wants to shake the world with the first-ever Powerball jackpot won using blockchain.
 
Looking ahead, there are many ways to make this better. On one hand, WeLottify will continue to improve trust by building user reputation with better identity and proof validations. On the other hand, WeLottify can make the game more fun and persuasive. Here are some ideas:
 
- expand to more lottery like MegaMillion, EuroMillion, etc
- in addition to Leader, allow Buyer where user / group can hire them to buy tickets and mail it. Powerball allows anyone to play. They just have to have possession of the real ticket.
- create ways for players to pick numbers and play them

**Team Members**:

Preferred Name: Tom Nguyen
Github Handle: @mrtomnguyen
Slack Username: @tomnguyen
Twitter Handle *optional*: @mrtomnguyen

Preferred Name: Vikas Singh
Github Handle: @vikas1188
Slack Username: @vikas

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
