### ISSUE TITLE
 Ethereum Chatbot

### ISSUE THREAD

**Issue by tcsiwula** [status-im/hackathon#42]
### Status Hackathon Submission

Type: Ethereum Chatbot 
Github Repo: https://github.com/tcsiwula/status_global_hackathon 
Description: A chatbot that will let you place orders to purchase Ethereum through the messenger platform and coinbase api.

Team Members:
------------------------------
Preferred Name: Tim
Github Handle: @tcsiwula
Slack Username: @tcsiwula
Twitter Handle: @tcsiwula
------------------------------
Preferred Name: Josh
Github Handle: @joshuabell
Slack Username: @joshua
Twitter Handle: @__joshuabell
------------------------------
Preferred Name: Zane
Github Handle: @zanewithspoon
Slack Username: @zanewithspoon
Twitter Handle: @zanewithspoon
------------------------------

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
