### ISSUE TITLE
Etherisc Flight Delay Chatbot Interface

### ISSUE THREAD

**Issue by kpii** [status-im/hackathon#44]
### Status Hackathon Submission

Type: Existing DApp 
Github Repo: https://github.com/etherisc/flightDelay 
Description: Chatbot interface for Flight Delay DApp to insure flights against delays or cancellations. See https://fdd.etherisc.com for the DApp with a web-based interface working on Ropsten Testnet. We are looking for developers who want to work with us on this, if you are interested please ping us on slack or leave a comment here. EDIT: We have now created a gitter channel for the team, join us on https://gitter.im/etherisc/dev-chatbot

Demo video: https://youtu.be/NYCGlLEtaXM

Team Members: 
Preferred Name: Joris
GitHub Handle: @jorisbontje
Slack Username: jorisbontje

Preferred Name: Juriaan
GitHub Handle: @sunfeld
Slack Username: jurrr

Preferred Name: Freek
GitHub handle: @freekp
Slack Username: freek

Preferred Name: Will
Github Handle: @wsaults
Slack Username: @wsaults

Preferred Name: Christoph
Github Handle: @christoph2806
Slack Username: christoph2806

Preferred Name: Stephan
Github Handle: @kpii
Slack Username: stephan
Twitter Handle: [@kpi](https://twitter.com/kpi)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by kpii** [comment]
Please join the team at https://gitter.im/etherisc/dev-chatbot
