### ISSUE TITLE
TBA

### ISSUE THREAD

**Issue by NPException** [status-im/hackathon#48]
### Status Hackathon Submission

Type: TBA
Github Repo: TBA
Description: TBA

Team Members:

Preferred Name: NPE
Github Handle: @NPException
Slack Username: @npexception
Twitter Handle: @NPException

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by NPException** [comment]
@commiteth, @jarradh: Is that "Deploying contract" probably broken? It's certainly taken longer than the "usual 1-2 minutes" by now. 😄

**Comment by tpatja** [comment]
@NPException: You are right, it was [broken](https://github.com/status-im/commiteth/issues/58). The bug was caused by the bot account's ETH balance running out and has now been fixed.
