### ISSUE TITLE
Block-Paper-Scissors

### ISSUE THREAD

**Issue by JasoonS** [status-im/hackathon#8]
### Status Hackathon Submission
Type: Dapp
Github Repo: https://github.com/JasoonS/Status-Hackathon
video: https://youtu.be/t5j_8EEOjoU
Description:
Bet bot is a decentralised betting app. Where users can create groups with friends and then use this in order to bet on 'trivial' things. The token system we are using is 0 sum, so some people have a negative balance of tokens and some have a positive. when all tokens in the system are added up the amount of tokens is 0. After a bet is settled I could have -5 tokens (the token type can be changed with each group by the user) and my friend could have 5. We could have decided to call our tokens beer tokens, and then someone with negative tokens can give someone with positive tokens -1 tokens and buy them a beer. thus I would have -4 tokens and my friend would have 4. This allows for a friendly way to manage your debts and all your previous bets. It also allows for additional functionallity, with the use case as if I go to a pub and forget my wallet. my friend could buy me some beers and I could give him 1 beer token for each beer he buys me. thus my balance would go to -2 and his would be 2. this would allow easy tracking of debts. All these use cases can be extended to any size group as long.

Team Members:
Preferred Name: Jason
Github Handle: @JasoonS
Slack Username: @JayBae

Preferred name: BrutishGuy 
Github handle: @BrutishGuy
Slack username: @brutishguy

Preferred Name: Yepster
Github Handle: @Yepster1
Slack Username: @Carysmall2295

Preferred Name: Roy
Github Handle: @RoyEyono
Slack Username: @RoyEyono

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)
